targets:
  $default:
    builders:
      functional_widget:
        enabled: true
        options:
          debugFillProperties: false
        generate_for:
          include:
            - lib/main.dart
            - lib/widgets/**.dart
            - lib/views/**.dart
      kiwi_generator:
        enabled: true
        generate_for:
          include:
            - lib/config/**.dart
      riverpod_generator:
        enabled: true
        generate_for:
          include:
            - lib/providers/**.dart
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'