name: sembast_client_flutter
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  crypto: ^3.0.2
  encrypt: ^5.0.1
  file_picker: ^5.2.2
  fluent_ui: ^4.0.3+1
  flutter_acrylic: ^1.0.0+2
  flutter_native_splash: ^2.2.15
  flutter_riverpod: ^2.1.1
  fpdart: ^0.3.0
  functional_widget_annotation: ^0.10.0
  kiwi: ^4.0.3
  niku: ^2.3.3
  one_context: ^2.1.0
  path: ^1.8.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  riverpod_annotation: ^1.0.6
  riverpod_context: ^0.3.0
  sembast: ^3.3.1
  shared_preferences: ^2.0.15
  tailwind_colors: ^0.3.1
  universal_html: ^2.0.8
  wave: ^0.2.2
  window_manager: ^0.2.7

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  functional_widget: ^0.10.1
  icons_launcher: ^2.0.6
  kiwi_generator: ^4.0.3
  riverpod_generator: ^1.0.6
  source_gen: ^1.2.6

flutter:
  uses-material-design: true