name: sembast_client_flutter
description: A Flutter client for basic manipulation of sembast database files

version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  code_editor: ^1.3.2
  conditioned: ^0.1.0-dev.1
  cross_file: ^0.3.3+2
  crypto: ^3.0.2
  day_night_switcher: ^0.2.0+1
  dio: ^4.0.6
  desktop_drop: ^0.4.0
  dotted_border: ^2.0.0+3
  encrypt: ^5.0.1
  feature_discovery: ^0.14.1
  file_picker: ^5.2.3
  flutter_acrylic: ^1.0.0+2
  flutter_json_view: ^1.0.0
  flutter_hooks: ^0.18.5+1
  flutter_pty: ^0.3.1
  flutter_riverpod: ^2.1.1
  fpdart: ^0.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  isolated_worker: ^0.1.1
  nester: ^1.2.1
  niku: ^2.3.3
  path: ^1.8.3
  path_provider: ^2.0.11
  random_color: ^1.0.6-nullsafety
  riverpod_context: ^0.3.0
  sembast: ^3.3.1
  shared_preferences: ^2.0.15
  xterm: ^3.4.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  icons_launcher: ^2.0.6
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: CascadiaCode
      fonts:
      - asset: assets/fonts/CascadiaCodePL.ttf