name: sembast_client_flutter
description: A Flutter client for basic manipulation of sembast database files

version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  conditioned: ^0.1.0-dev.1
  cross_file: ^0.3.3+2
  crypto: ^3.0.2
  day_night_switcher: ^0.2.0+1
  desktop_drop: ^0.4.0
  dotted_border: ^2.0.0+3
  encrypt: ^5.0.1
  file_picker: ^5.2.3
  flutter_acrylic: ^1.0.0+2
  flutter_json_view: ^1.0.0
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.2.16
  flutter_riverpod: ^2.1.1
  fpdart: ^0.3.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  isolated_worker: ^0.1.1
  nester: ^1.2.1
  niku: ^2.3.3
  path: ^1.8.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  riverpod_context: ^0.3.0
  sembast: ^3.3.1
  shared_preferences: ^2.0.15
  tailwind_colors: ^0.3.1
  wave: ^0.2.2

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  icons_launcher: ^2.0.6
  injectable_generator: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/